apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: effectops
resources:
  - namespace.yaml
  - configmap.yaml
  - rabbitmq.yaml
  - api.yaml
  - web.yaml
  - network-policy.yaml
  - hpa.yaml

